var annotated_dup =
[
    [ "beam", "structbeam.html", "structbeam" ],
    [ "beamcolor", "structbeamcolor.html", "structbeamcolor" ],
    [ "colordata", "structcolordata.html", "structcolordata" ],
    [ "DebugmallocData", "struct_debugmalloc_data.html", "struct_debugmalloc_data" ],
    [ "DebugmallocEntry", "struct_debugmalloc_entry.html", "struct_debugmalloc_entry" ],
    [ "DinStr", "struct_din_str.html", "struct_din_str" ],
    [ "enemyarmada", "structenemyarmada.html", "structenemyarmada" ],
    [ "enemyship", "structenemyship.html", "structenemyship" ],
    [ "enemysquadronship", "structenemysquadronship.html", "structenemysquadronship" ],
    [ "gameassets", "structgameassets.html", "structgameassets" ],
    [ "gameattributes", "structgameattributes.html", "structgameattributes" ],
    [ "inputstateinterface", "structinputstateinterface.html", "structinputstateinterface" ],
    [ "keymap", "structkeymap.html", "structkeymap" ],
    [ "leveldtt", "structleveldtt.html", "structleveldtt" ],
    [ "mouseposition", "structmouseposition.html", "structmouseposition" ],
    [ "phaserbeam", "structphaserbeam.html", "structphaserbeam" ],
    [ "playership", "structplayership.html", "structplayership" ],
    [ "shipdtt", "structshipdtt.html", "structshipdtt" ],
    [ "spritemapdata", "structspritemapdata.html", "structspritemapdata" ],
    [ "star", "structstar.html", "structstar" ],
    [ "starcolor", "structstarcolor.html", "structstarcolor" ],
    [ "starmap", "structstarmap.html", "structstarmap" ],
    [ "texturedata", "structtexturedata.html", "structtexturedata" ],
    [ "torpedocolors", "structtorpedocolors.html", "structtorpedocolors" ],
    [ "torpedoshot", "structtorpedoshot.html", "structtorpedoshot" ]
];