var files_dup =
[
    [ "data_transfer_types.h", "data__transfer__types_8h.html", "data__transfer__types_8h" ],
    [ "debugmalloc.h", "debugmalloc_8h.html", "debugmalloc_8h" ],
    [ "enemy_ship.c", "enemy__ship_8c.html", "enemy__ship_8c" ],
    [ "enemy_ship.h", "enemy__ship_8h.html", "enemy__ship_8h" ],
    [ "file_management.c", "file__management_8c.html", "file__management_8c" ],
    [ "file_management.h", "file__management_8h.html", null ],
    [ "game_assets.h", "game__assets_8h.html", "game__assets_8h" ],
    [ "game_attributes.h", "game__attributes_8h.html", "game__attributes_8h" ],
    [ "game_engine.c", "game__engine_8c.html", "game__engine_8c" ],
    [ "game_engine.h", "game__engine_8h.html", "game__engine_8h" ],
    [ "graphics.c", "graphics_8c.html", "graphics_8c" ],
    [ "graphics.h", "graphics_8h.html", "graphics_8h" ],
    [ "hit_management.c", "hit__management_8c.html", "hit__management_8c" ],
    [ "hit_management.h", "hit__management_8h.html", null ],
    [ "input_state_interface.h", "input__state__interface_8h.html", "input__state__interface_8h" ],
    [ "keymap.h", "keymap_8h.html", "keymap_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "phaser.c", "phaser_8c.html", "phaser_8c" ],
    [ "phaser.h", "phaser_8h.html", "phaser_8h" ],
    [ "player_ship.c", "player__ship_8c.html", "player__ship_8c" ],
    [ "player_ship.h", "player__ship_8h.html", "player__ship_8h" ],
    [ "random_number_in_interval.c", "random__number__in__interval_8c.html", "random__number__in__interval_8c" ],
    [ "random_number_in_interval.h", "random__number__in__interval_8h.html", "random__number__in__interval_8h" ],
    [ "star_map.c", "star__map_8c.html", "star__map_8c" ],
    [ "star_map.h", "star__map_8h.html", "star__map_8h" ],
    [ "string_operations.c", "string__operations_8c.html", "string__operations_8c" ],
    [ "string_operations.h", "string__operations_8h.html", "string__operations_8h" ],
    [ "texture_data.h", "texture__data_8h.html", "texture__data_8h" ],
    [ "torpedo.c", "torpedo_8c.html", "torpedo_8c" ],
    [ "torpedo.h", "torpedo_8h.html", "torpedo_8h" ],
    [ "ui_input.c", "ui__input_8c.html", "ui__input_8c" ],
    [ "ui_input.h", "ui__input_8h.html", "ui__input_8h" ]
];